- name: Add Grafana APT key (Ubuntu/Debian)
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add Grafana APT repo (Ubuntu/Debian)
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Grafana on Debian/Ubuntu
  apt:
    name: grafana
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# --------------------------- Amazon Linux / RedHat 系列 ---------------------------

- name: Add Grafana YUM repository (Amazon Linux / RedHat)
  yum_repository:
    name: grafana
    description: Grafana Stable Repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    enabled: yes
  when: ansible_os_family in ["RedHat", "Amazon"]

- name: Install Grafana on Amazon Linux / RedHat
  package:
    name: grafana
    state: present
  when: ansible_os_family in ["RedHat", "Amazon"]

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Test role load
  debug:
    msg: "Role grafana is active"
