# roles/fluentbit/tasks/main.yml
- name: Add Fluent Bit repo for Amazon Linux 2023
  get_url:
    url: https://packages.fluentbit.io/fluentbit.key
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-fluentbit

- name: Create Fluent Bit repo file
  copy:
    dest: /etc/yum.repos.d/fluentbit.repo
    content: |
      [fluentbit]
      name=Fluent Bit
      baseurl=https://packages.fluentbit.io/amazonlinux/2023
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fluentbit
      enabled=1

- name: Install Fluent Bit
  dnf:
    name: td-agent-bit
    state: present

- name: Enable and start Fluent Bit
  systemd:
    name: td-agent-bit
    enabled: yes
    state: started

- name: Deploy Fluent Bit config
  copy:
    dest: /etc/td-agent-bit/td-agent-bit.conf
    content: |
      [SERVICE]
          Flush        1
          Log_Level    info
          Parsers_File parsers.conf
          HTTP_Server  On
          HTTP_Listen  0.0.0.0
          HTTP_Port    2020

      [INPUT]
          Name         tail
          Path         /var/log/messages,/var/log/secure
          Parser       syslog
          Tag          host.*

      [OUTPUT]
          Name  es
          Match *
          Host  127.0.0.1
          Port  9200
          Index fluentbit
          Type  _doc
