- name: Create Prometheus user and directories
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move binaries
  copy:
    src: "/tmp/prometheus-2.51.2.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy configs and consoles
  copy:
    src: "/tmp/prometheus-2.51.2.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: "0644"
    remote_src: yes
  loop:
    - prometheus.yml
    - consoles
    - console_libraries

- name: Set up Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Prometheus
  systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
    state: started

- name: Test role load
  debug:
    msg: "Role prometheus is active"
